### ISSUE TITLE
not pulling a camera serial number - 220

### ISSUE THREAD

**Issue by tdodson90** [Skyofazure06/checkcoroner#2]
Ran checkCoroner.sh against the attached coroner, and it did not print out a serial for the Camera. Looking through the coroner, I do see a camera attached with a serial number of JR6819007B5D3

camera found on this line:
/var/camera/2/sn_camera = "JR6819007B5D3"

attaching coroner and output file
[error.zip](https://github.com/tdodson90/checkcoroner/files/646315/error.zip)

**Comment by SkySai** [comment]
This is caused by the possibility of having multiple cameras. 
At the moment we simply grab like .. output line 2. 

$ cat pref1.txt | grep sn_camera
/var/camera/0/sn_camera = "none"
/var/camera/2/sn_camera = "JR6819007B5D3"
/var/camera/3/sn_camera = "none"

We need to throw all of that data into an array and then iterate over it outputting if NOT "none"

**Comment by SkySai** [comment]
new version uploaded; 
Resolved for the 220s. 

There will probably be a similar issue with icon 800s as currently we are only checking for info.camera.hdmi0.serialnumber without any additional logic. 

Please open new issue for icon 800 if you encounter it.
